### ISSUE TITLE
Matches.

### ISSUE THREAD

**Issue by mrc4tt** [Contentify/Contentify#395]
Hi.

So soon i try make "Matches" or just  only clicking on "Matches"

I getting this error:

> Sorry, something bad happened. Our website has crashed.
> 
> Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!

What can i do?

**Comment by chriskonnertz** [comment]
Hello,

1. Go to th teams section. Ensure there is at least one team that is a "gaming" team.
2. You could turn on the debug mode, then you will see the error message. Or take a look at the error log file: `storage/log/laravel.log`

**Comment by mrc4tt** [comment]
@chriskonnertz 

Seems i found the error in log:
`[2018-07-01 23:01:52] production.ERROR: ErrorException: sizeof(): Parameter must be an array or an object that implements Countable in /var/www/beta/contentify/ModelHandler.php`

**Comment by chriskonnertz** [comment]
I assume this is just a test installtion? It would be great if you send me a dump of your database so I might be able to reproduce this potential bug. EmaiL `contentifycms@gmail.com`

**Comment by mrc4tt** [comment]
@chriskonnertz I dont understand, why it show this:
```
Sorry, something bad happened. Our website has crashed.
Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!
```

If i clicking "Matches" > and i have disabled debug.
app.php:
```
'env' => env('APP_ENV', 'production'),
'debug' => env('APP_DEBUG', false),

```

So what. can i do?

**Comment by chriskonnertz** [comment]
Turn on the debug mode:
`'debug' => env('APP_DEBUG', false),`
Then try again and you should get a detailled error message.
Then copy it and paste it here.
Then deactivate the debug mode again.

**Comment by chriskonnertz** [comment]
> I dont understand, why it show this:

This is for security reasons. If the debug mode is turned off (it should be turned off usually) then none error descripitions will be displayed to make it more difficult to attack the website.

**Comment by mrc4tt** [comment]
Hey @chriskonnertz - screenshot here. 


![](https://i.gyazo.com/f312d75da719791769075423d4042ad2.png)

**Comment by mrc4tt** [comment]
@chriskonnertz - can u check???

**Comment by chriskonnertz** [comment]
Done. Did you change something in this file? `app/Modules/matche/Http/Controller/AdminMatchesController.php`? Please compare with this: https://github.com/Contentify/Contentify/blob/v2.4/app/Modules/Matches/Http/Controllers/AdminMatchesController.php

You can use this online tool to compare the files: https://www.diffchecker.com/

**Comment by chriskonnertz** [comment]
If both are equal: Did you install 2.4 or upgrade to 2.4 from an older version?

Because I do not understand why/how there can be an error in line 233 of the `ModelHandler` class if you did not modify the `AdminMatchesController.php` file.

**Comment by mrc4tt** [comment]
Hi @chriskonnertz - i did only installed the 2.4. ;) and i dont have modify the file. since it's give same error. i have try reinstall the database. ;/

**Comment by chriskonnertz** [comment]
Ok. Well, I've added  a piece of code that should solve the problem:
https://github.com/Contentify/Contentify/commit/bcee140332116aca57e32fe5e91f0ac980d669a5

**Comment by mrc4tt** [comment]
Seems it works now 👍

**Comment by mrc4tt** [comment]
@chriskonnertz Seems i found more errors under admin-backend.

**Comment by mrc4tt** [comment]
errors under: website > Teams > Create new.

![](https://i.gyazo.com/553a29eec32a35b06e47a78849b16e49.png)

![](https://i.gyazo.com/553a29eec32a35b06e47a78849b16e49.png)

**Comment by chriskonnertz** [comment]
Hm, these are old errors that (should) have been fixed. It seems like one of the release .zip files is outdated. Please can you tell me where you downloaded Contentify?

Also please tell me if these changes are in your files? https://github.com/Contentify/Contentify/commit/cdbfeb6fce3d0b5a0f82b5595203cd3c32a766f1

**Comment by mrc4tt** [comment]
@chriskonnertz i did downloaded from here: https://github.com/Contentify/Contentify/releases/tag/v2.4 

And no! it's not changed from the https://github.com/Contentify/Contentify/commit/cdbfeb6fce3d0b5a0f82b5595203cd3c32a766f1

**Comment by mrc4tt** [comment]
@chriskonnertz bug found:

Under Admin backend > Esports content > Matches > I fill anyway. but UNDER the "Match Scores" > and if i set de_dust2 and score: 16:0 >> i getting only this error: Error: Request failed.Message: "error" only that.

**Comment by chriskonnertz** [comment]
Please take a look at this change: Is it in you files? https://github.com/Contentify/Contentify/commit/c30c4e1df0b97b7c590379425a5fdfed6409dc11

**Comment by mrc4tt** [comment]
Hi @chriskonnertz 

I have try change the file as you pointed. still didnt worked.

I'm still getting this error, so soon i have set 5:0 score about i use apply or save.. i getting same error:

`Error: Request failed.Message: "error"`

**Comment by chriskonnertz** [comment]
Yep, I get this error as well.

**Comment by chriskonnertz** [comment]
Now it's gone. Want to know why? Because my browser still had old JavaScript files in the cache. When I forced it to reload them the new code started to work and thus the error disappeared. Please try to clear the cache of your browser. How to clear it depends on your browser, but you may try `SHIFT`+`F5` or pressing `F5` multiple times.
